name: Musser Scout Reservation
title: Musser Scout Reservation
logo: "/img/logo.png"
description: "The Musser camping experience includes a variety of program ventures including Cub summer camp options, exciting year-round programs, and diverse training courses for Scouts and Scouters of all ages."

#alert:
#  text: Text for site wide alerts
#  class: Set alert class (default: alert-warning)

plugins:
  - octopress-paginate
  - jekyll_picture_tag
  - jekyll/minibundle
  - jekyll-contentblocks

url: http://127.0.0.1:4000
baseurl:

picture:
  nomarkdown: false
  suppress_warnings: true

recaptcha: 6LdmHcIUAAAAAMMBaaQiAMhIn25IwZQC7Xeb2byD

permalink: /news/:title

pagination:
  limit: false
  per_page: 6
  title_suffix: " - Page :num"
