name: Musser Scout Reservation
title: Musser Scout Reservation
logo: "/img/logo.png"
description: "The Musser camping experience includes a variety of program ventures including Cub summer camp options, exciting year-round programs, and diverse training courses for Scouts and Scouters of all ages."

alert:
  text: Following Pennsylvania Gov. Tom Wolf’s order issued on Thursday, March 12 closing schools, community centers, and other venues in Montgomery County, the <strong>Cradle of Liberty Council is postponing all activities at the Musser Scout Reservation until further notice.</strong> Please visit <a href="http://colbsa.org/coronavirus">colbsa.org/coronavirus</a> for the most up-to-date weekend and summer guidance regarding Coronavirus.
  class: alert-primary

plugins:
  - octopress-paginate
  - jekyll_picture_tag
  - jekyll/minibundle
  - jekyll-contentblocks

url: http://127.0.0.1:4000
baseurl:

picture:
  nomarkdown: false
  suppress_warnings: true

recaptcha: 6LdmHcIUAAAAAMMBaaQiAMhIn25IwZQC7Xeb2byD

permalink: /news/:title

pagination:
  limit: false
  per_page: 6
  title_suffix: " - Page :num"
